Add relation_fields to Prefetcher class
tinkoffjournal/freddie pull request #8
Opened 2022-01-13 10:24 UTC by FlyLikeSoarin

Default value is set to empty list
If relateion_fields list contains values (relation attribute names) -
these attributes are added to prefetched objects (dicts or objects)

2022-01-18 13:55 UTC, arsgab requested changes

2022-01-18 13:55 UTC, arsgab commented on freddie/db/queries.py
> +    relation_fields: List[str] = []
А почему обязательно `List`? Тут же любой `Iterable` подойдет

2022-01-18 13:55 UTC, arsgab commented on freddie/db/queries.py
> +    relation_fields: List[str] = []
Я бы сделал `relation_fields: Iterable[str] = ()`

2022-01-24 00:21 UTC, FlyLikeSoarin commented on freddie/db/queries.py
> +    relation_fields: List[str] = []
Исправил

2022-01-24 00:22 UTC, FlyLikeSoarin commented
Добавил тесты, но никак не могу их локально запустить. Может стоит добавить компоуз для проекта или дописать в README как развернуть локальное окружение?

2022-02-02 08:32 UTC, arsgab approved these changes

2022-02-02 08:33 UTC, merged